# Generated by Django 3.1.5 on 2021-03-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='pay.OrderItem'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
