# Generated by Django 3.1.5 on 2021-03-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='quantity'),
        ),
    ]
