# Generated by Django 3.1.5 on 2021-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_auto_20210318_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
    ]
