# Generated by Django 3.1.5 on 2021-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_auto_20210318_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='item', to='pay.OrderItem'),
        ),
    ]
