# Generated by Django 3.1.5 on 2021-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_auto_20210318_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_on_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
