# Generated by Django 3.1.5 on 2021-03-03 12:26

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210302_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_us',
            name='created_on',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='call_us',
            name='created_on_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
