# Generated by Django 3.1.5 on 2021-03-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210303_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_us',
            name='created_on_time',
        ),
    ]
