# Generated by Django 3.1.5 on 2021-01-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_model', models.CharField(default='', max_length=255)),
                ('mobile_img', models.ImageField(default='', upload_to='mobile')),
                ('Screen size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Product code', models.CharField(default='', max_length=255, unique=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('mobile_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mobile_brand', verbose_name='Mobile_Brand')),
            ],
        ),
    ]
