# Generated by Django 3.1.5 on 2021-01-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210123_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Screen size',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
