# Generated by Django 3.1.5 on 2021-01-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210123_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Screen size',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
