# Generated by Django 3.1.5 on 2021-01-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210124_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_slug',
            field=models.SlugField(default='', max_length=40, unique=True),
        ),
    ]
