# Generated by Django 3.1.5 on 2021-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_slug',
        ),
        migrations.AddField(
            model_name='mobile',
            name='mobile_url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='mobile_brand',
            name='brand_url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
