# Generated by Django 3.1.5 on 2021-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210124_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile_url',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile_brand',
            name='brand_url',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_url',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
