# Generated by Django 3.1.5 on 2021-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210124_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Product code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
