# Generated by Django 3.1.5 on 2021-01-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210124_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='mobile_url',
        ),
    ]
