# Generated by Django 3.1.5 on 2021-01-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_mobile_mobile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_url',
        ),
        migrations.AddField(
            model_name='mobile',
            name='mobile_url',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
