# Generated by Django 3.1.5 on 2021-01-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210124_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='mobile_url',
        ),
        migrations.RemoveField(
            model_name='mobile_brand',
            name='brand_url',
        ),
    ]
