# Generated by Django 3.1.5 on 2021-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210124_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_brand',
            name='brand_url',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
