# Generated by Django 3.1.5 on 2021-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_mobile_brand_brand_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='Mobile_url',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
