# Generated by Django 3.1.5 on 2021-01-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_mobile_mobile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_url',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
