# Generated by Django 3.1.5 on 2021-01-28 08:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=60)),
                ('category_url', models.SlugField(default='', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Mobile_Brand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_url',
            new_name='product_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.AddField(
            model_name='product',
            name='Product code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='Screen size',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='mobile'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[(' ', 'موجود'), ('un', 'ناموجود')], max_length=2, null=True, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='category'),
        ),
    ]
