# Generated by Django 3.1.5 on 2021-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210128_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product code',
            new_name='product code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Screen size',
        ),
        migrations.AddField(
            model_name='product',
            name='product screen size',
            field=models.CharField(default='', max_length=4),
        ),
    ]
