# Generated by Django 3.1.5 on 2021-03-03 12:07

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210303_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
