# Generated by Django 3.1.5 on 2021-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210303_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on_time',
            field=models.TimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
