# Generated by Django 3.1.5 on 2021-03-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_comment_created_on_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_on_time',
        ),
    ]
