# Generated by Django 3.1.5 on 2021-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_comment_created_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status_number',
            field=models.IntegerField(null=True, verbose_name='موجودی انبار'),
        ),
    ]
