# Generated by Django 3.1.5 on 2021-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_product_status_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status_number',
            field=models.IntegerField(default=0, verbose_name='موجودی انبار'),
        ),
    ]
