# Generated by Django 3.1.5 on 2021-03-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20210311_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
    ]
